users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX6IhMQFJIaAasQaO78JdSg2sSEFaSHN4Ur4q70ar/GBWqYpD9uDQPbC+Rw5oUo0cF24Nw9TlLziMQiW3SAUP9kn5EyHA10FaTQZHFKN56L4JrfHR3FMVnEPqqAQfx2EyaoN8f9rVa0VdRywyPC4rp3PDylaFzOiHISGSFqQdriQOJB2LHDul49DLRDA78BwLlKvqoULd7XgAgK1SAmlDq9oKNhaCWWcYchJHgcIzlWn/I8QPxVQ4d/KvnoZ5dDPVgKSffbuvWs/MnWd7AeJVJ6tPQni0Sq0Os36uiR5Ll2aaFt56lXOgaPa5/iHrmEWIHjX4D9ki1L1G4yXWgWgwZ5ZOC+6q1G9cTcHW8xQi/TxxHh9mw7F3g0ni6Q6VQ9D7Yc0Hb0DJg8FgOELSs+n7cCphi4xzPDas+Cf/2ZyDxULjlkuki2FqJ1IAO45e3x1J5b22Fivw4+xv7OoLPGTQLCjbao9y2+ZYCshC6Q5jP07+vBdzd1FfIKtzGFiPqWMk= ubuntu
